services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFrontendJSG
    container_name: frontendJSG
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
    networks:
      - redwebJSG

  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackendJSG
    container_name: backendJSG
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:rw
      - /app/vendor
    networks:
      - redwebJSG

  web:
    build:
      context: ./web
      dockerfile: DockerfileWebJSG
    container_name: webJSG
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - redwebJSG

networks:
  redwebJSG:
    driver: bridge 